CREATE TABLE IF NOT EXISTS assets (
    id BIGSERIAL PRIMARY KEY NOT NULL,
    name TEXT NOT NULL UNIQUE,
    unit_value DOUBLE PRECISION NOT NULL CHECK (unit_value >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
